server:
  port: 8082

spring:
  sleuth:
    enabled: true
    otel:
      config:
        trace-id-ratio-based: 1.0
      exporter:
        otlp:
          enabled: true
          #send span via gRPC to Jeager collector
          endpoint: http://localhost:4317
    baggage:
      remote-fields:
        - bg-field1
        - bg-field2
        - bg-field3
        - bg-field4
      correlation-enabled: true
      correlation-fields:
        - col-field
    messaging:
      jms:
        enabled: true
  application:
    name: Service-B
#